version: '3.9'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - .:/var/www/
      - ./config1/Nginx:/etc/nginx/sites-enabled/